name: Auto Assign and Limit Issues
on:
  issues:
    types: [labeled, opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
      - name: Auto Assign for bug
        uses: wow-actions/auto-assign@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          assignees: ajay-dhangar
          includeLabels: bug

      - name: Auto Assign for enhancement
        uses: wow-actions/auto-assign@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          assignees: ajay-dhangar
          includeLabels: enhancement

  limit-issues:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
      - name: Limit number of issues per user
        uses: ./.github/actions/issue-limit
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
