name: Auto Assign and Issue Limit

on:
  issues:
    types: [opened, edited]
    # Trigger on issue opened or edited events
  pull_request:
    types: [opened, edited]
    # Trigger on pull request opened or edited events
  issue_comment:
    types: [created]
    # Trigger on new comments on issues or pull requests

jobs:
  auto_assign_and_check_limit:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - name: Check for /assign command and active issues limit
      id: check_assign_command_and_limit
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const body = context.payload.comment.body;
          const isIssue = context.payload.issue !== undefined;
          const isPullRequest = context.payload.pull_request !== undefined;
          const issueOrPrNumber = isIssue ? context.payload.issue.number : context.payload.pull_request.number;
          const assignees = body.match(/\/assign(?:\s+@([^\s]+))?/);

          // Fetch active issues count
          const { owner, repo } = context.repo;
          const response = await github.issues.listForRepo({
            owner,
            repo,
            state: 'open'
          });

          const activeIssues = response.data.filter(issue => !issue.pull_request).length;

          if (assignees) {
            const assignee = assignees[1] || 'Ajay-Dhangar'; // Default assignee if not specified in command
            core.setOutput('assignee', assignee);
            core.setOutput('issueOrPrNumber', issueOrPrNumber);
          } else {
            core.setOutput('assignee', '');
            core.setOutput('issueOrPrNumber', '');
          }

          core.setOutput('activeIssues', activeIssues);
    
    - name: Auto-assign issue or PR and check issue limit
      if: steps.check_assign_command_and_limit.outputs.issueOrPrNumber != '' && steps.check_assign_command_and_limit.outputs.activeIssues < 4
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const assignee = '${{ steps.check_assign_command_and_limit.outputs.assignee }}';
          const issueOrPrNumber = '${{ steps.check_assign_command_and_limit.outputs.issueOrPrNumber }}';

          const response = await github.issues.addAssignees({
            issue_number: issueOrPrNumber,
            owner: context.repo.owner,
            repo: context.repo.repo,
            assignees: [assignee]
          });

          console.log(response);
