name: Auto Assign

on:
  issues:
    types: [opened, edited]
    # Trigger on issue opened or edited events
  pull_request:
    types: [opened, edited]
    # Trigger on pull request opened or edited events
  issue_comment:
    types: [created]
    # Trigger on new comments on issues or pull requests

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      # Ensure write permissions are granted

    steps:
    - name: Check for /assign command
      id: check_assign_command
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const isCommentEvent = context.eventName === 'issue_comment';
          let assignee = '';
          let issueOrPrNumber = '';

          if (isCommentEvent) {
            const body = context.payload.comment.body;
            const assignees = body.match(/\/assign(?:\s+@([^\s]+))?/);
            if (assignees) {
              assignee = assignees[1] || 'Ajay-Dhangar'; // Default assignee if not specified in command
              issueOrPrNumber = context.payload.issue ? context.payload.issue.number : context.payload.pull_request.number;
            }
          }

          core.setOutput('assignee', assignee);
          core.setOutput('issueOrPrNumber', issueOrPrNumber);

    - name: Auto-assign issue or PR
      if: steps.check_assign_command.outputs.issueOrPrNumber != ''
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const assignee = '${{ steps.check_assign_command.outputs.assignee }}';
          const issueOrPrNumber = '${{ steps.check_assign_command.outputs.issueOrPrNumber }}';

          const response = await github.issues.addAssignees({
            issue_number: issueOrPrNumber,
            owner: context.repo.owner,
            repo: context.repo.repo,
            assignees: [assignee]
          });

          console.log(response);
