name: Issue Creation Workflow

on:
  issues:
    types: [opened]

jobs:
  check-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Retrieve Contributor's Open Issues
        id: retrieve-issues
        run: |
          ISSUE_COUNT=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/search/issues?q=is:open+author:${{ github.event.issue.user.login }}+repo:${{ github.repository }}" | jq -r '.total_count')
          echo "::set-output name=issue_count::$ISSUE_COUNT"

      - name: Comment if User Has More than 3 Open Issues
        if: steps.retrieve-issues.outputs.issue_count > 3
        run: |
          curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"body":"Hi @${{ github.event.issue.user.login }}, you currently have more than 3 open issues. We recommend addressing them before creating new ones. Thank you!"}' \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments"
