name: Label PR Workflow

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

jobs:
  label-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Label Pull Request
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"labels":["CodeHarborHub - Pull Request!"]}' \
          "https://api.github.com/repos/${{ github.repository }}/issues/${ PR_NUMBER }"
